//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelApplicationMadera.DonneesLocales.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Composant()
        {
            this.LigneDevis = new HashSet<LigneDevis>();
            this.Module = new HashSet<Module>();
        }
    
        public int id { get; set; }
        public string nature { get; set; }
        public decimal image_produit { get; set; }
        public string couleur_dessin { get; set; }
        public double prix_HT { get; set; }
        public int stock { get; set; }
        public int quantite_limite_de_stock_pour_commande_auto { get; set; }
        public int nombre_de_composant_par_commande { get; set; }
        public bool commande_auto_active { get; set; }
        public string nom { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int id_unite_dusage { get; set; }
        public int id_caracteristique { get; set; }
        public Nullable<int> id_fournisseur { get; set; }
        public string nom_famille { get; set; }
    
        public virtual Caracteristique Caracteristique { get; set; }
        public virtual FamilleDeComposant FamilleDeComposant { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual UniteDusage UniteDusage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LigneDevis> LigneDevis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Module> Module { get; set; }
    }
}
