//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelApplicationMadera.DonneesLocales.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Huisserie
    {
        public int id { get; set; }
        public string descriptif { get; set; }
        public string qualite { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string nom { get; set; }
        public decimal coupe_de_principe { get; set; }
        public decimal cctp { get; set; }
        public System.DateTime created_at_module { get; set; }
        public System.DateTime updated_at_module { get; set; }
        public int id_caracteristique { get; set; }
        public int id_unite_dusage { get; set; }
        public string nom_famille { get; set; }
    
        public virtual Caracteristique Caracteristique { get; set; }
        public virtual FamilleDeModule FamilleDeModule { get; set; }
        public virtual Module Module { get; set; }
        public virtual UniteDusage UniteDusage { get; set; }
    }
}
