//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelApplicationMadera.DonneesLocales.Entites
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDDAPPLICATIONMADERAEntities : DbContext
    {
        public BDDAPPLICATIONMADERAEntities()
            : base("name=BDDAPPLICATIONMADERAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BureauEtude> BureauEtude { get; set; }
        public virtual DbSet<Caracteristique> Caracteristique { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<CommandeClient> CommandeClient { get; set; }
        public virtual DbSet<CommandeFournisseur> CommandeFournisseur { get; set; }
        public virtual DbSet<Commercial> Commercial { get; set; }
        public virtual DbSet<Composant> Composant { get; set; }
        public virtual DbSet<Comptable> Comptable { get; set; }
        public virtual DbSet<Devis> Devis { get; set; }
        public virtual DbSet<EcheanceDePaiement> EcheanceDePaiement { get; set; }
        public virtual DbSet<Facture> Facture { get; set; }
        public virtual DbSet<FamilleDeComposant> FamilleDeComposant { get; set; }
        public virtual DbSet<FamilleDeModule> FamilleDeModule { get; set; }
        public virtual DbSet<FamilleGamme> FamilleGamme { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<Gamme> Gamme { get; set; }
        public virtual DbSet<Huisserie> Huisserie { get; set; }
        public virtual DbSet<LigneDevis> LigneDevis { get; set; }
        public virtual DbSet<ModePaiement> ModePaiement { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<Paiement> Paiement { get; set; }
        public virtual DbSet<Projet> Projet { get; set; }
        public virtual DbSet<StatutDevis> StatutDevis { get; set; }
        public virtual DbSet<UniteDusage> UniteDusage { get; set; }
        public virtual DbSet<UserMadera> UserMadera { get; set; }
    }
}
