//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelApplicationMadera.DonneesLocales.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.BureauEtude = new HashSet<BureauEtude>();
            this.Gamme = new HashSet<Gamme>();
            this.Composant = new HashSet<Composant>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public decimal coupe_de_principe { get; set; }
        public decimal cctp { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int id_caracteristique { get; set; }
        public int id_unite_dusage { get; set; }
        public string nom_famille { get; set; }
    
        public virtual Caracteristique Caracteristique { get; set; }
        public virtual FamilleDeModule FamilleDeModule { get; set; }
        public virtual Huisserie Huisserie { get; set; }
        public virtual UniteDusage UniteDusage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BureauEtude> BureauEtude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gamme> Gamme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Composant> Composant { get; set; }
    }
}
